# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_stackoverflow_wrappers", use_symbols = TRUE, package_name = "stackoverflow")

#' @docType package
#' @usage NULL
#' @useDynLib stackoverflow, .registration = TRUE
NULL

#' Trigger Stack Overflow
#' @export
stack_overflow_list <- function(x) .Call(wrap__stack_overflow_list, x)

#' @export
stack_overflow_list_dbls <- function(x) .Call(wrap__stack_overflow_list_dbls, x)

